### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by akamob** [RussellSB/automated-gait-analysis#3]
Hi, Thank you for the great work.

I want to build a gait analysis framework that detect keypoints of human body and distinguish human identity by analyzing their gait. I'm wondering if it is possible that use your code to achieve it?

Could you give me some suggestions to use your code? or is there any tutorials?

May I have your suggestions?
Any help is much appreciated:)

**Comment by RussellSB** [comment]
Hi akamob!

I've done this project quite a while ago. I don't have much of a direct code tutorial write up for it, but I did write a whole document on it for my BSc thesis which could benefit you on how to use it, as well as some literature review done at the time.

If you request access here saying it's you, I can accept it for you: https://www.um.edu.mt/library/oar/handle/123456789/64176

Kind regards,
Russell

**Comment by akamob** [comment]
Hi, @RussellSB, Thank you so much for sharing!

I have sent messages to you:) For verification, my e-mail is: a930544@gmail.com
I will try to test and if I have some new problems then I would contact you again.

And thank you again.
akamob

**Comment by Hujujuyu** [comment]
Aloha, My name is Christine, and I am interested in this program. I would like to see the thesis to know how to use the code. Can you help me with that?
